### ISSUE TITLE
Restriction of spaces over tabs in poo_checks.xml

### ISSUE THREAD

**Issue by Mr-Vinti** [oop-pub/oop-asignments#18]
I suggest commenting the 66th line of the file:
`<module name="FileTabCharacter"/>`

Using tabs over spaces shouldn't be a coding style error, only a preference. We all know the war between spaces and tabs users, don't ignite the fire.

**Comment by laurentiustamate94** [comment]
@Mr-Vinti we will discuss this in the team and I will come up with an answer here 👍

**Comment by laurentiustamate94** [comment]
We discussed for over a year and we decided that we will remain to Tabs as a preference for all the assignments we create.

Personal bragging: you can watch [this](https://www.youtube.com/watch?v=SsoOG6ZeyUI)
